CREATE TABLE SAMPLE_ORG  (
	ID BIGINT NOT NULL,
	NAME VARCHAR(32) NOT NULL
) ;

CREATE TABLE SAMPLE_TAG  (
	ID BIGINT NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL
) ;

INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (1, '테스트1');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (2, '테스트2');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (3, '테스트3');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (4, '테스트4');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (5, '테스트5');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (6, '테스트6');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (7, '테스트7');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (8, '테스트8');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (9, '테스트9');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (10, '테스트10');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (11, '테스트11');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (12, '테스트12');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (13, '테스트13');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (14, '테스트14');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (15, '테스트15');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (16, '테스트16');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (17, '테스트17');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (18, '테스트18');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (19, '테스트19');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (20, '테스트20');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (21, '테스트21');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (22, '테스트22');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (23, '테스트23');
INSERT INTO SAMPLE_ORG (ID, NAME) VALUES (24, '테스트24');
